# Generated by Django 4.1.7 on 2023-03-18 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_due', models.DateField()),
                ('time_of_due', models.DateTimeField()),
                ('status', models.CharField(choices=[(1, 'To do'), ('In Progress', 'In Progress'), (3, 'Done')], default=1, max_length=50)),
                ('category', models.ManyToManyField(to='api.category')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('date_of_creation', models.DateTimeField(auto_now=True)),
                ('email', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
